src/Entity/Task.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 * @ORM\Table(name="tasks")
 */
class Task implements \JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max = 255, maxMessage = "Name of task cannot be longer than {{ limit }} characters")
     * @Assert\NotBlank
     */
    private ?string $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max = 255, maxMessage = "Description of task cannot be longer than {{ limit }} characters")
     */
    private ?string $description;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Range(min = 1, max = 5, notInRangeMessage = "You must choose between {{ min }} and {{ max }} priority levels")
     */
    private ?int $priority_level;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Date
     */
    private ?\DateTime $date_completion;

    /**
     * @ORM\Column(type="blob", nullable=true)
     * @Assert\File()
     */
    private $file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriorityLevel(): ?int
    {
        return $this->priority_level;
    }

    public function setPriorityLevel(int $priority_level): self
    {
        $this->priority_level = $priority_level;

        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getDateCompletion(): ?\DateTimeInterface
    {
        return $this->date_completion;
    }

    /**
     * @param \DateTimeInterface $date_completion
     * @return Task
     */
    public function setDateCompletion(\DateTimeInterface $date_completion): Task
    {
        $this->date_completion = $date_completion;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getFile(): ?\DateTime
    {
        return $this->file;
    }

    /**
     * @param $file
     * @return $this
     */
    public function setFile( $file): Task
    {
        $this->file = $file;
        return $this;
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'priority_level' => $this->priority_level,
            'date_completion' => $this->date_completion,
        ];
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('priority_level')
            ->add('date_completion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/Api/TaskController.php
<?php

namespace App\Controller\Api;

use App\Repository\TaskRepository;
use App\Service\TaskService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TaskController
 *
 * @package App\Controller
 * @Route("/api", name="tasks_api")
 */
class TaskController extends AbstractController
{
    /**
     * @param TaskRepository $taskRepository
     * @return JsonResponse
     * @Route("/tasks", name="tasks", methods={"GET"})
     */
    public function getTasks(TaskRepository $taskRepository): JsonResponse
    {
        $data = $taskRepository->findAll();
        return $this->response($data);
    }

    /**
     * @param Request $request
     * @param TaskService $taskService
     * @return JsonResponse
     *
     * @Route("/tasks", name="tasks_create", methods={"POST"})
     */
    public function createTask(Request $request, TaskService $taskService): JsonResponse
    {
        try {
            $request = $this->transformJsonBody($request);
            $data = $request->request->all();

            $file = $request->files->get('file') ?? null;

            $errors = $taskService->createTask($data, $file);

            if (empty($errors)) {
                $responseCode = Response::HTTP_CREATED;
                $responseData = [
                    'status' => $responseCode,
                    'result' => "Task added successfully",
                ];
                return $this->response($responseData);
            } else {
                $responseCode = Response::HTTP_BAD_REQUEST;
                $responseData = [
                    'status' => $responseCode,
                    'errors' => $errors,
                ];
            }
            return $this->response($responseData, $responseCode);
        } catch (\Exception $exception) {
            $responseCode = Response::HTTP_INTERNAL_SERVER_ERROR;
            $responseData = [
                'status' => $responseCode,
                'errors' => [$exception->getMessage()],
            ];
        }
        return $this->response($responseData, $responseCode);
    }

    /**
     * @param TaskRepository $taskRepository
     * @param int $id
     * @return JsonResponse
     * @Route("/tasks/{id}", name="tasks_get", methods={"GET"})
     */
    public function getTask(TaskRepository $taskRepository, int $id): JsonResponse
    {
        $task = $taskRepository->find($id);
        if (!$task){
            $data = [
                'status' => Response::HTTP_NOT_FOUND,
                'errors' => "Task not found",
            ];
            return $this->response($data, Response::HTTP_NOT_FOUND);
        }
        return $this->response($task);
    }

    /**
     * @param Request $request
     * @param TaskService $taskService
     * @param int $id
     * @return JsonResponse
     * @Route("/tasks/{id}", name="tasks_put", methods={"PATCH"})
     */
    public function updateTask(Request $request, TaskService $taskService, int $id): JsonResponse
    {
        try {
            $request = $this->transformJsonBody($request);
            $data = $request->request->all();
            $errors = $taskService->updateTask($data, $id);

            if (empty($errors)) {
                $responseCode = Response::HTTP_OK;
                $responseData = [
                    'status' => $responseCode,
                    'result' => "Task updated successfully",
                ];
                return $this->response($responseData);
            } else {
                $responseCode = Response::HTTP_BAD_REQUEST;
                $responseData = [
                    'status' => $responseCode,
                    'errors' => $errors,
                ];
            }
            return $this->response($responseData, $responseCode);
        } catch (\InvalidArgumentException $invalidArgumentException) {
            $responseCode = Response::HTTP_BAD_REQUEST;
            $responseData = [
                'status' => $responseCode,
                'errors' => [$invalidArgumentException->getMessage()],
            ];
        } catch (\Exception $exception) {
            $responseCode = Response::HTTP_INTERNAL_SERVER_ERROR;
            $responseData = [
                'status' => $responseCode,
                'errors' => [$exception->getMessage()],
            ];
        }
        return $this->response($responseData, $responseCode);
    }

    /**
     * @param Request $request
     * @param TaskService $taskService
     * @param int $id
     * @return JsonResponse
     * @Route("/tasks/{id}/validate", name="tasks_put", methods={"POST"})
     */
    public function validateTask(Request $request, TaskService $taskService, int $id): JsonResponse
    {
        try {
            $taskService->validateTask($id);

            $responseCode = Response::HTTP_OK;
            $responseData = [
                'status' => $responseCode,
                'result' => "Task validated successfully",
            ];
            return $this->response($responseData);
        } catch (\InvalidArgumentException $invalidArgumentException) {
            $responseCode = Response::HTTP_BAD_REQUEST;
            $responseData = [
                'status' => $responseCode,
                'errors' => [$invalidArgumentException->getMessage()],
            ];
        } catch (\Exception $exception) {
            $responseCode = Response::HTTP_INTERNAL_SERVER_ERROR;
            $responseData = [
                'status' => $responseCode,
                'errors' => [$exception->getMessage()],
            ];
        }
        return $this->response($responseData, $responseCode);
    }

    /**
     * @param EntityManagerInterface $entityManager
     * @param TaskRepository $taskRepository
     * @param int $id
     * @return JsonResponse
     * @Route("/tasks/{id}", name="tasks_delete", methods={"DELETE"})
     */
    public function deleteTask(EntityManagerInterface $entityManager, TaskRepository $taskRepository, int $id): JsonResponse
    {
        $task = $taskRepository->find($id);

        if (!$task){
            $data = [
                'status' => Response::HTTP_NOT_FOUND,
                'errors' => "Task not found",
            ];
            return $this->response($data, Response::HTTP_NOT_FOUND);
        }

        $entityManager->remove($task);
        $entityManager->flush();
        $data = [
            'status' => Response::HTTP_OK,
            'result' => "Task deleted successfully",
        ];
        return $this->response($data);
    }

    /**
     *  Returns a JSON response
     *
     * @param $data
     * @param int $status
     * @param array $headers
     * @return JsonResponse
     */
    public function response($data, int $status = Response::HTTP_OK, array $headers = []): JsonResponse
    {
        return new JsonResponse($data, $status, $headers);
    }

    /**
     * @param Request $request
     * @return Request
     */
    protected function transformJsonBody(Request $request): Request
    {
        $data = json_decode($request->getContent(), true);

        if ($data === null) {
            return $request;
        }

        $request->request->replace($data);

        return $request;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tasks")
 */
class TaskController extends AbstractController
{
    /**
     * @Route("/", name="task_index", methods={"GET"})
     */
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('tasks/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="task_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('task_index');
        }

        return $this->render('tasks/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_show", methods={"GET"})
     */
    public function show(Task $task): Response
    {
        return $this->render('tasks/show.html.twig', [
            'task' => $task,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="task_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('task_index');
        }

        return $this->render('tasks/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('task_index');
    }
}

templates/tasks/_delete_form.html.twig
<form method="post" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tasks/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tasks/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/tasks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <h1>Task index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Priority_level</th>
                <th>Date_completion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.priorityLevel }}</td>
                <td>{{ task.dateCompletion ? task.dateCompletion|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('task_new') }}">Create new</a>
{% endblock %}

templates/tasks/new.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <!-- Main content -->
    <div class="content-wrapper">

        <!-- Content area -->
        <div class="content">

            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Add Task</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="collapse"></a>
                            <a class="list-icons-item" data-action="reload"></a>
                            <a class="list-icons-item" data-action="remove"></a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <p class="mb-4"></p>

                    <form id="new-task-form" action="#">
                        <fieldset>
                            <legend class="text-uppercase font-size-sm font-weight-bold">Data</legend>

                            <div class="form-group">
                                <label for="name" class="col-form-label">Name</label>
                                <input id="name" name="name" type="text" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label for="description" class="col-form-label">Description</label>
                                <textarea id="description" name="description" class="form-control" placeholder="Insert a description"></textarea>
                            </div>

                            <div class="form-group row">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label for="priority-level" class="col-form-label">Priority Level</label>
                                        <input id="priority-level" name="priority_level" type="number" class="form-control" min="1" max="5" required>
                                    </div>
                                </div>

                                <div class="col-6">
                                    <div class="form-group">
                                        <label for="date-completion" class="col-form-label">Date Completion</label>
                                        <input id="date-completion" name="date_completion" class="form-control" type="date" value="">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="file" class="col-form-label">Upload File</label>
                                <input id="file" name="file" class="form-control" type="file" formenctype="multipart/form-data">
                            </div>
                        </fieldset>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /form inputs -->

            <div class="card">
                <div class="table-responsive">
                    <table id="tasks" class="table table-hover table-striped datatable-tasks">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Priority Level</th>
                            <th>Date Completion</th>
                            <th class="text-right">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td colspan="10" class="text-center">Loading...</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /content area -->
    </div>
    <!-- /main content -->
{% endblock %}

{% block javascript_extras %}
    <!-- Theme JS files -->
    <script src="{{ asset('js/demo_pages/form_inputs.js') }}"></script>

    <script>
        let tasks = [];

        function listTasks()
        {
            $.ajax(
                "/api/tasks",
                {
                    dataType: "json",
                    method: "GET",
                    cache: false,
                    success: function ( data, textStatus, jqXHR ) {
                        if (!Array.isArray(data)) {
                            alert('No tasks found');
                            return;
                        }
                        tasks = data;
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus + (errorThrown ? '\r\n' + errorThrown : ''));
                    },
                    complete: function () {
                        loadTasksTable();
                    }
                }
            );
        }

        function validateTask(id)
        {
            $.ajax(
                "/api/tasks/" + id + "/validate" ,
                {
                    dataType: "json",
                    method: "POST",
                    cache: false,
                    success: function ( data, textStatus, jqXHR ) {
                        alert(data.result);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus + (errorThrown ? '\r\n' + errorThrown : ''));
                    },
                    complete: function () {
                        listTasks();
                    }
                }
            );
        }

        function deleteTask(id)
        {
            $.ajax(
                "/api/tasks/" + id ,
                {
                    dataType: "json",
                    method: "DELETE",
                    cache: false,
                    success: function ( data, textStatus, jqXHR ) {
                        alert(data.result);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus + (errorThrown ? '\r\n' + errorThrown : ''));
                    },
                    complete: function () {
                        listTasks();
                    }
                }
            );
        }

        function loadTasksTable()
        {
            table = $('#tasks').DataTable({
                destroy: true,
                data: tasks,
                "columns": [
                    { "data": "name" },
                    { "data": "description" },
                    { "data": "priority_level" },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            if (data.date_completion) {
                                return data.date_completion.date
                            }
                            return '';
                        }
                    },
                    {
                        "className": 'text-right text-nowrap',
                        "data": null,
                        "render": function(data, type, row, meta) {
                            let result = '';

                            if (data.date_completion === null) {
                                result += `<button class="btn btn-outline-warning btn-validate btn-xs" title="Validate"
                                        value="${data.id}">Validate</button>`;
                            }

                            result += `<a class="btn btn-outline-info btn-xs" title="Edit"
                                        href="/tasks/edit/${data.id}">Edit</a>`;

                            result += `<button class="btn btn-outline-danger btn-delete btn-xs" title="Delete"
                                        value="${data.id}">Delete</button>`;

                            return result;
                        }
                    },
                ],
                // "order": [[0, 'asc']],
                "columnDefs": [
                    {
                        orderable: false,
                        targets: [4],
                        type: 'html',
                    }
                ],
            });
        }

        $(document).ready(function() {
            listTasks();

            let form = $("#new-task-form");

            form.submit(event => {
                event.preventDefault();

                var formData = new FormData();

                let name = form.find("#name").val();
                let description = form.find("#description").val();
                let priority_level = form.find("#priority-level").val();
                let date_completion = form.find("#date-completion").val();

                formData.append('name', name);
                formData.append('description', description);
                formData.append('priority_level', priority_level);
                formData.append('date_completion', date_completion);

                if (form.find("#file")[0] != null) {
                    formData.append('file', form.find("#file")[0].files[0]);
                }

                $.ajax({
                    url: '/api/tasks',
                    data: formData,
                    type: 'POST',
                    contentType: false, // NEEDED, DON'T OMIT THIS (requires jQuery 1.6+)
                    processData: false, // NEEDED, DON'T OMIT THIS
                    success: function ( data, textStatus, jqXHR ) {
                        alert('Task Inserted');
                        listTasks();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus + (errorThrown ? '\r\n' + errorThrown : ''));
                    },
                });
            });

            $('#tasks').on('click', '.btn-validate', event => {
                validateTask(event.target.value);
            });
            $('#tasks').on('click', '.btn-delete', event => {
                deleteTask(event.target.value);
            });
        });
    </script>
{% endblock %}

templates/tasks/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Priority_level</th>
                <td>{{ task.priorityLevel }}</td>
            </tr>
            <tr>
                <th>Date_completion</th>
                <td>{{ task.dateCompletion ? task.dateCompletion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('task_index') }}">back to list</a>

    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}